# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5742fe3ad1d720795edd24d31d598477dd7ec7ffe635b9d4b0f49395639d0a0dc43cfc61f5626d24795e0bf5e748597eb26551ea129335ef0c5a2155467af01e

test:
  secret_key_base: f1787963c0f6ee24aad105d1e6f5edcbfef0539851bcf61a37993af7e090f7596668c7db5ab97193db3947ae5de994490fabc3bd2902a20e7de36dcb7d1b7556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
